apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxdb
  name: influxdb
  namespace: kube-system
spec:
  replicas: 1
  selector:
    name: influxdb
  template:
    metadata:
      labels:
        name: influxdb
    spec:
      hostNetwork: true
      nodeSelector:
        node: master
      containers:
      - name: influxdb
        image: master:5000/influxdb
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}